# Build Node Workflow
#
# Based on Starter Workflow Here
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# Workflow name
name: Build Node

# Run only on pushes and pull requests on main branch, as well as tags
# https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

# Define a single job named build
jobs:
  build:
    # Run job on Ubuntu runner
    runs-on: ubuntu-latest

    # Give all permissions
    permissions: write-all

    # Job Steps
    steps:
      # Step 1 - Checkout the Repository
      # https://github.com/actions/checkout
      - name: 1 - Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # ----------------------------------------------------------
      # THESE ONLY RUN IF NEW TAG IS PUSHED - WILL CREATE RELEASE
      # ----------------------------------------------------------

      # Step 6 - Log In to GitHub Container Registry
      # https://github.com/docker/login-action
      - name: 6 - Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 7 - Build and Push Docker Image
      # https://github.com/docker/build-push-action
      - name: 7 - Build and Push Docker Image
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dev-cas-server:latest

      # Step 8 - Make Release on GitHub
      # https://github.com/softprops/action-gh-release
      - name: 8 - Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true

      
      # Step 4 - Notify Discord for Deploy
      - name: Discord Deploy
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Build Complete! Starting Deploy..."

      # Step 5 - Deploy App
      - name: Deploy Stage
        id: request
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://watchtower.cs.ksu.edu/v1/update'
          method: 'GET'
          bearerToken: ${{ secrets.DEPLOY_TOKEN }}
          timeout: 600000

      # Step 6 - Show Response
      - name: Show Response
        run: echo ${{ steps.request.outputs.response }}
